config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  get "dreams/new_audio", to: "dreams#new_audio", as: :create_new_audio
  post "dreams/new_audio", to: "dreams#new_audio", as: :new_audio_dreams
  post 'dreams/new_answered_questions', to: 'dreams#new_answered_questions', as: 'new_answered_questions'
  resources :questions
  resources :answers, only: [:create, :update ]
  resources :dream_questions
  resources :dreams do
    collection do
      get :analytics
    end
    member do
      post :new_answered_questions
    end
  end
  resources :labels
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :dream_questions
  validates_presence_of :question_text
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    if Dream.todays_dream(current_user)
      @dream_of_today = Dream.todays_dream(current_user)
    # else
    #   @dream_of_today = Dream.create(user: current_user, date: Date.today)
    end
      @questions = Question.where(user: current_user).or(Question.where(original: true)).order(:id)
    end

    def new
      @question = Question.new
    end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    @question.correct = false

    if @question.save!
      redirect_to questions_path, notice: 'Your question was saved!'
    else
      render :new
    end


  end

  def show
    set_question
  end

  def edit
  end

  def destroy

    @question.destroy
    redirect_to questions_path, status: :see_other
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:question_text)
  end
end

app/views/questions/index.html.erb
<div class="container p-2 text-white">
  <div class="d-flex justify-content-between">
    <%= link_to "↩", root_path, class: "btn button_one text-white" %>
    <% if @dream_of_today.present? %>
      <%= button_to 'Generate Dream', new_answered_questions_dream_path(@dream_of_today), method: :post, class: "btn button_one text-white" %>
    <% else %>
      <%= button_to 'Generate Dream', new_answered_questions_path, method: :post, class: "btn button_one text-white" %>
    <% end %>
  </div>

  <div class="container opacity-box mt-4 p-4" style="display: grid !important;">

    <% @questions.each do |question| %>
      <div class="question-opacity-card">
        <%= question.question_text %>
      </div>

        <% answer = DreamQuestion.find_by(dream: @dream_of_today, question: question)&.answer || Answer.new %>
        <%= simple_form_for(answer, url: answer.new_record? ? dream_questions_path : url_for(answer), method: answer.new_record? ? :post : :patch, remote: true) do |f| %>
          <div class="textarea-container">
            <%= f.input :user_answer, label: "✏️",
            input_html: {
              class: 'form-control transparent-textarea',
            } %>
          </div>
          <div class="buttons-container">
            <%= f.submit answer.new_record? ? "Add answer" : "Update answer", class: "btn button_one" %>
          </div>
          <%= f.input :dream_id, as: :hidden, input_html: {value: @dream_of_today.id } if @dream_of_today.present? %>
          <%= f.input :question_id, as: :hidden, input_html: {value: question.id } %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h2>Type your question</h2>

<%= simple_form_for(@question) do |f| %>
<%= f.input :question_text %>
<%= f.submit %>
<% end %>

<button type="button">delete</button>
<%= link_to "return", questions_path %>

app/views/questions/show.html.erb
<%= @question.question_text %>
<%= @question.explanation_text %>

app/views/questions/temp.html.erb
<% @questions_data.each do |question| %>
  <% if question.user_id == current_user.id %>
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= question.question_text %></h6>
        <p class="card-text">
          <div>
            <%= question.explanation_text.truncate(200)%>
          </div>
        </p>
        <% if question.correct == false %>
          <%= link_to "Edit", edit_question_path(question), class: "card-link" %>
          <%= link_to "Delete", question_path(question), method: :delete, data: { confirm: "Are you sure?" }, class: "card-link" %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>