config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  get "dreams/new_audio", to: "dreams#new_audio", as: :create_new_audio
  post "dreams/new_audio", to: "dreams#new_audio", as: :new_audio_dreams
  post 'dreams/new_answered_questions', to: 'dreams#new_answered_questions', as: 'new_answered_questions'
  resources :questions
  resources :answers, only: [:create, :update ]
  resources :dream_questions
  resources :dreams do
    collection do
      get :analytics
    end
    member do
      post :new_answered_questions
    end
  end
  resources :labels
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  has_many :dream_questions, dependent: :destroy
  has_many :answers, through: :dream_questions, dependent: :destroy
  has_many :dream_labels, dependent: :destroy
  has_many :labels, through: :dream_labels

  default_scope { order(created_at: :desc) }

  def self.todays_dream(current_user)
    dream = Dream.where(user: current_user, date: Time.current.beginning_of_day..Time.current.end_of_day).first
    dream ||= Dream.create(user: current_user, date: Time.current)
    Rails.logger.info "todays_dream called with user: #{current_user.inspect}, dream: #{dream.inspect}"
    dream
  end

  def self.create_with_audio(current_user)
    Dream.create(user: current_user, date: Time.current)
  end

  def set_dream_title
    client = OpenAI::Client.new
    gpt_response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [{
          role: "user",
          content: "Please generate a short title for this #{content}, not longer than 20 character."
        }]
      })
    new_title = gpt_response&.dig("choices", 0, "message", "content")
    new_title = "Your Dream" if new_title.nil?
    update(title: new_title) if new_title
    return new_title
  end

  def generate_content_from_answers
    # Collect all answers from this dream

    answered_questions = self.dream_questions.select { |dq| dq.answer.present? }
    answers_content = answered_questions.map do |dq|
      "#{dq.question.question_text}: #{dq.answer.user_answer}"
    end

    # Set up the OpenAI client
    client = OpenAI::Client.new
    # Call the OpenAI API
    gpt_response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [{
          role: "user",
          content: "Please generate short text that link the questions and answers that is not adding anything that wasnt mentioned: #{answers_content.join(', ')}"
        }]
      })

    generated_content = gpt_response&.dig("choices", 0, "message", "content")
    if generated_content.nil?
      generated_content = answers_content.join(', ')
    end
    # Return the generated content
    generated_content
  end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  before_action :set_dream, only: %i[show destroy edit update]

  def index
    if params[:search]
      @dreams = Dream.where("content LIKE ?", "%#{params[:search]}%")
    else
      @dreams = Dream.where(user: current_user)
    end
      @dreams.each do |dream|
        dream.set_dream_title if dream.title.nil?
      end
  end

  def new
    @dream = Dream.new
    @labels = Label.all
  end

  def new_audio
    @dream_of_today = Dream.create_with_audio(current_user)
    if params[:audio].present?
      audio_file = params[:audio].tempfile
      transcript = OpenaiService.transcribe(audio_file)
      render json: { transcription: transcript}
    end
  end

  def new_answered_questions
    # Find the dream or create a new one if it doesn't exist
    @dream = Dream.find_by(id: params[:id]) || Dream.create(user: current_user, date: Date.today)

    # Generate the dream content
    generated_content = @dream.generate_content_from_answers

    # Update the dream's content
    @dream.update(content: generated_content)

    redirect_to @dream
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    @dream.date = Date.today
    generate_dream_labels(@dream, params[:dream][:label_ids])
    if @dream.save!
      redirect_to dreams_path, notice: 'Your dream was saved!💭'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    # Destroy all dream_labels
    @dream.dream_labels.destroy_all
    # Regenerate all the dream_labels
    generate_dream_labels(@dream, params[:dream][:label_ids])
    if @dream.update!(dream_params)
      redirect_to dream_path(@dream)
    else
      render :edit
    end
  end

  def destroy
    @dream.id = params[:id]
    @dream.destroy!
    redirect_to dreams_path, status: :see_other
  end

  def analytics
    @label_counts = Label.joins(:dreams).group('labels.name').count
    @dream_counts = Dream.where(user: current_user).size

  end

  private

  def generate_dream_labels(dream, label_ids)
    unless label_ids.nil?
      label_ids.each do |label_id|
        unless label_id.empty?
          DreamLabel.create(label: Label.find(label_id), dream: dream)
        end
      end
    end
  end

  def set_dream
    @dream = Dream.find(params[:id])
  end

  def dream_params
    params.require(:dream).permit(:content, :label_ids)
  end
end

app/views/dreams/_answer_fields.html.erb
<div class="textarea-container">
  <%= f.input :user_answer, label: "✏️", input_html: { class: 'form-control transparent-textarea' } %>
</div>
<div class="buttons-container">
  <%= f.submit "Update answer", class: "btn button_one" %>
</div>

app/views/dreams/analytics.html.erb
<div class="container">
  <%= link_to "↩", root_path, class: "btn button_one text-white" %>
    <h1 class="title">My Profile 🌌</h1>
    <div class="d-flex justify-content-center mt-3">
      <img src="https://images.unsplash.com/photo-1490814525860-594e82bfd34a?q=80&w=2521&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" style="border-radius: 50%; width: 100px; height: 100%;" alt="User Image">
    </div>
    <div class="opacity-box p-4">
      <h4><%= current_user.username %></h4>
      <br>
      <p>🚀 <%= current_user.current_goal %></p>
      <p>🍷 <%= current_user.current_influences %></p>
      <p>💭 <%= current_user.current_dreams %></p>
    </div>

  <div class="analytics-container">
    <h2>Dream Analytics</h2>
    <div id="dream-chart">
      <canvas id="dreamPieChart" data-controller="analytics"
              data-analytics-labels-value="<%= @label_counts.keys %>"
              data-analytics-data-value="<%= @label_counts.values %>">
      </canvas>
    </div>

    <h2>Dream Count</h2>
      <div class="dream-count">
        <%= @dream_counts %>
    </div>
  </div>
  <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link bottom-icons" %>
</div>

app/views/dreams/edit.html.erb
<div class="container p-3 text-white">
  <%= link_to "↩", dreams_path, class: "btn button_one" %>

  <h1><%="Edit your dream from #{@dream.date} 🌙"%></h1>

  <%= simple_form_for(@dream) do |f| %>
  <%= f.association :labels, as: :check_boxes %>
  <%= f.input :content %>
  <%= f.submit %>
  <% end %>

  <div class="buttons-container">
    <%= link_to 'Delete', dream_path(@dream), class: "btn button_one", data: { "turbo-method": :delete } %>
    <%= link_to 'Add a label', edit_dream_path(@dream), class: "btn button_one" %>
  </div>
</div>

app/views/dreams/index.html.erb
<div class="container">
  <div class="wrap">
    <div class="box">
      <%= form_tag dreams_path, method: :get, class: "search" do %>
        <div class="d-flex justify-content-between align-items-center">
          <%= text_field_tag :search, params[:search], class: "input", placeholder: " Search", onmouseout: "this.value = ''; this.blur();" do %>
          <i class="fas fa-filter"></i>
          <% end %>
          <i class="fas fa-filter"></i>
        </div>
        <% end %>
    </div>
  </div>

  <div class="cards-container">
    <% @dreams.each do |dream| %>
      <%=link_to dream_path(dream) do %>

        <div class="index-opacity-box">

          <div class="index-date-container">
            <%= dream.date.strftime('%d.%m.%Y') %>
            </div>
          <div class="index-promt-container">
            <%= dream.title.delete('"') %>
            </div>
          <div class="index-dream-content-container">
              <%= dream.content.truncate(300) if dream.content%>
          </div>
          <div class="tags">
            <% dream.labels.each do |label| %>
              <div class="tag"><%= label.name %></div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
   </div>
  </div>
</div>

app/views/dreams/new.html.erb
<div class="container">

  <%= link_to "↩", root_path, class: "btn button_one text-white" %>

  <div class="cards-container">

    <div class="opacity-box">

      <%# DATE %>
        <div class="date-container" style='color: #b5aebe; font: 20px;'>
          <h5><%= Date.today.strftime('%d.%m.%Y') %></h5>
        </div>

      <%# TAGS %>
      <div style="margin-top: 50px;">
      </div>


      <%= simple_form_for(@dream) do |f| %>

        <%= f.association :labels,
        as: :check_boxes,
        legend_tag: false,
        input_html: { class: "tag-selector" },
        item_wrapper_class: 'tag-item' %>

      <%# Text DREAM %>
      <div class="index-dream-content-container">
          <%= f.input :content, input_html: {
          # class: 'form-control transparent-textarea',
          style: 'height: 250px;
                  background-color: transparent;
                  border: transparent;'
        },
        label: "My dream",
        placeholder:
          "Describe your dream..." %>
      </div>

      <%# BUTTON  %>
      <div class="buttons-container">
      <%= f.submit "✔", class: "btn button_one" %>
      </div>

      <% end %>

     </div>
  </div>


      <script>
        document.addEventListener('input', function(event) {
          if (event.target.classList.contains('auto-grow')) {
            event.target.style.height = 'auto';
            event.target.style.height = (event.target.scrollHeight) + 'px';
          }
        });
      </script>
</div>

app/views/dreams/new_audio.html.erb
    <img src="<%= asset_url("moth.png")%>" alt="" class="moth">

<div class="container" data-controller="audio-input">

  <div class="wrap">
    <div class="box">
      <%= link_to "↩", root_path, class: "btn button_one text-white" %>
    </div>
  </div>

  <div class="new-recording-opacity-box">

    <div class="new-recording-title-container">
          <h2> Record your dream ... </h2>
      </div>

       <div class="new-recording-content-container">
          <%= form_with url: create_new_audio_path, local: true, multipart: true, method: :post do |form| %>
            <%= form.hidden_field :audio, data: { audio_input_target: "input" }%>
          <% end %>

          <textarea
            style='
                  color: #b5aebe;
                  background-color: transparent;
                  border: transparent;
                  width: 100%;
                  height: 200px;'
            class='form-control'
            placeholder='Describe your dream...'
            id="transcribedText"
            data-audio-input-target="transcribedText">
          </textarea>
        </div>


        <div class="tags">
          <%= link_to '#', class: "btn button_one violet button--mic",
            data: {
              action: "click->audio-input#toggleRecording",
              audio_input_target: "recordButton" } do %>
            <i class="fa fa-microphone record-icon" style="font-size: 50px;"></i>
          <% end %>
        </div>


  </div>

    <div class="tags">
      <%= simple_form_for @dream_of_today do |f| %>
        <%= f.input :content, as: :hidden, input_html: { data: { audio_input_target: "transcribedText" } } %>
        <%= f.submit "Save", class: "btn button_one" %>
      <% end %>
    </div>


  </div>

</div>

app/views/dreams/show.html.erb
<div class="container p-3 text-white">
    <%= link_to "↩", dreams_path, class: "btn button_one" %>

  <div class="row mt-4">
  </div>

<div class="container dream_container opacity-box p-3">
  <h3><%= @dream.date.strftime("%d %B %Y") %></h3>
    <div class="tags">
      <% @dream.labels.each do |label| %>
        <div class="tag"><%= label.name %></div>
      <% end %>
    </div>
    <% if @dream.content %>
      <p><%= @dream.content %></p>
    <% else %>
      <p>No content for this dream 🤷🏽‍♀️</p>
    <% end %>

  <p>
    <%= link_to dream_path(@dream), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "card-link" do %>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>

    
    <span style="margin: 0 5px;"></span>

  <%= link_to edit_dream_path(@dream), class: "card-link" do %>
      <i class="fa-regular fa-pen-to-square" style="color: #575489;"></i>
    <% end %>
  </p>
    </div>
</div>