config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "up" => "rails/health#show", as: :rails_health_check

  get "dreams/new_audio", to: "dreams#new_audio", as: :create_new_audio
  post "dreams/new_audio", to: "dreams#new_audio", as: :new_audio_dreams
  post 'dreams/new_answered_questions', to: 'dreams#new_answered_questions', as: 'new_answered_questions'
  resources :questions
  resources :answers, only: [:create, :update ]
  resources :dream_questions
  resources :dreams do
    collection do
      get :analytics
    end
    member do
      post :new_answered_questions
    end
  end
  resources :labels
end

app/views/pages/home.html.erb
<% current_hour = Time.now.hour %>
<% if current_hour < 12 %>
  <h1 class="title mt-5 mb-5"><%= "Good Morning, #{current_user.username}"%>!🌤️</h1>
<% elsif current_hour < 18 %>
  <h1 class="title mt-5 mb-5"><%= "Good Afternoon, #{current_user.username}"%>!🌞</h1>
<% elsif current_hour < 22 %>
  <h1 class="title mt-5 mb-5"><%= "Good Evening, #{current_user.username}"%>!🌟</h1>
<% else %>
  <h1 class="title mt-5 mb-5"><%= "Good Night, #{current_user.username}"%>!🌙</h1>
<% end %>

<p class="date"><%= "#{Date.today.strftime('%A, %B %d, %Y')}" %></p>

<div class="d-flex justify-content-center">
  <button type="button" class="button home-buttons-container-1">
    <%= link_to new_dream_path do %><i class="fa-solid fa-pen"></i><% end %>
  </button>
</div>

<div class="d-flex justify-content-around mt-4">
  <button type="button" class="button home-buttons-container">
    <%= link_to create_new_audio_path do %>
      <i class="fa-solid fa-microphone-lines"></i>
    <% end %>
  </button>
  <button type="button" class="button home-buttons-container">
    <%= link_to questions_path do %><i class="fa-solid fa-question"></i><% end %>
  </button>
</div>